### PR TITLE
Fixes to work with Gatling 2.2.2

### PR DESCRIPTION
**Pull request by jpescalona**
This may make this project works now :)

### CODE REVIEW

**Comment by LuboVarga** [comment]
Thanks. Seems working (some tests done). Going to use it in "production". I will give feedback for sure here.

I have also merged it to master.

Running has triggered some problem:
`
11:59:21.062 [INFO ] i.g.c.s.w.LogFileDataWriter - Initialized
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.gatling.mojo.MainWithArgsInFile.runMain(MainWithArgsInFile.java:50)
	at io.gatling.mojo.MainWithArgsInFile.main(MainWithArgsInFile.java:33)
Caused by: akka.actor.InvalidActorNameException: actor name [AmqpManage] is not unique!
	at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:129)
	at akka.actor.dungeon.Children$class.reserveChild(Children.scala:130)
	at akka.actor.ActorCell.reserveChild(ActorCell.scala:374)
	at akka.actor.dungeon.Children$class.makeChild(Children.scala:268)
	at akka.actor.dungeon.Children$class.attachChild(Children.scala:46)
	at akka.actor.ActorCell.attachChild(ActorCell.scala:374)
	at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:732)
	at io.gatling.amqp.config.AmqpVariables$class.setupVariables(AmqpVariables.scala:32)
	at io.gatling.amqp.config.AmqpProtocol.setupVariables(AmqpProtocol.scala:40)
	at io.gatling.amqp.config.AmqpProtocol.warmUp(AmqpProtocol.scala:77)
	at io.gatling.amqp.config.AmqpProtocol$$anon$1$$anonfun$newComponents$1.apply(AmqpProtocol.scala:26)
	at io.gatling.amqp.config.AmqpProtocol$$anon$1$$anonfun$newComponents$1.apply(AmqpProtocol.scala:24)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.comps$1(Protocol.scala:59)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.io$gatling$core$protocol$ProtocolComponentsRegistry$$$anonfun$4(Protocol.scala:61)
	at io.gatling.core.protocol.ProtocolComponentsRegistry$lambda$$components$1.apply(Protocol.scala:61)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.components(Protocol.scala:61)
	at io.gatling.amqp.action.AmqpActionBuilder.components(AmqpActionBuilder.scala:13)
	at io.gatling.amqp.action.AmqpActionBuilder.build(AmqpActionBuilder.scala:18)
	at io.gatling.core.structure.StructureBuilder$class.io$gatling$core$structure$StructureBuilder$class$$$anonfun$1(StructureBuilder.scala:34)
	at io.gatling.core.structure.StructureBuilder$class$lambda$$build$1.apply(StructureBuilder.scala:33)
	at io.gatling.core.structure.StructureBuilder$class$lambda$$build$1.apply(StructureBuilder.scala:33)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at io.gatling.core.structure.StructureBuilder$class.build(StructureBuilder.scala:33)
	at io.gatling.core.structure.ScenarioBuilder.build(ScenarioBuilder.scala:38)
	at io.gatling.core.structure.PopulationBuilder.build(ScenarioBuilder.scala:101)
	at io.gatling.core.scenario.SimulationParams.io$gatling$core$scenario$SimulationParams$$$anonfun$13(Simulation.scala:169)
	at io.gatling.core.scenario.SimulationParams$lambda$$scenarios$1.apply(Simulation.scala:169)
	at io.gatling.core.scenario.SimulationParams$lambda$$scenarios$1.apply(Simulation.scala:169)
	at scala.collection.immutable.List.map(List.scala:277)
	at io.gatling.core.scenario.SimulationParams.scenarios(Simulation.scala:169)
	at io.gatling.app.Gatling.run(Gatling.scala:102)
	at io.gatling.app.Gatling.runIfNecessary(Gatling.scala:75)
	at io.gatling.app.Gatling.start(Gatling.scala:65)
	at io.gatling.app.Gatling$.start(Gatling.scala:57)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:49)
	at io.gatling.app.Gatling$.main(Gatling.scala:43)
	at io.gatling.app.Gatling.main(Gatling.scala)
	... 6 more
`

**Comment by jpescalona** [comment]
No problem. I just also worked in a way to replace values inside the message body that comes from session data. Do you know if this is already implemented?

**Comment by LuboVarga** [comment]
I have fix of given exception (release 0.8, also on master branch).

I am not sure, what are you asking. If you want to send message with use of session (for example login from feeder), you can use construct like this:
```
    amqp("import customer")
      .publish(
        customerExchange.name,
        body = Left({ session =>
          customerJson(session(ID_KEY).as[String], session(MARKET_ID).as[String], session(NAME_ID).as[String], session(PASSWD_ID).as[String])
        }),
        headers = Map("Payload" -> "Customer")
      )
```

If you input generates some amqp publishing to another exchange, you can wait for it (and measure processing latency) by code like this:
```
    amqp("check Customer")
      .consumeSingle(
        customerChangesQueue.name,
        correlationId = session => {
          "urn:customer:" + session(ID_KEY).as[String]
        },
        customCorrelationIdTransformer = msg => {
          msg.deliveredMsg.properties.getHeaders.get("PayloadId") + ""
        }
      )
```

response is correlated by custom correlation id (it is in headers). I hope I have not crippled example by copy/pasting.

**Comment by jpescalona** [comment]
Yes, I think that also will work for me, but I was thinking something like using ${variable} inside msg body like gatling http requests, for example:

`{
    "profileId": "${profileId}",
    "anotherKey": "${anotherKeyValue}"
}
`
having defined the values for profileId and anotherKey in session, and then those values be replaced automatically before inserting the message in the queue/exchange, making this substitution completely abstract to the user.

**Comment by LuboVarga** [comment]
Hmmm, I have never used gatling http capability. It would be nice to have possibility like you have written.

PS: Current master is failing to receive amqp message with correlationId. It just timeouts. I am not sure, if I would have time to find bug and fix it. Have it in mind that it is not working.

**Comment by jpescalona** [comment]
I've already done it. Let me do a new PR with this change.

BTW, I just using insert messages functionality, anyway i will take a look into the code if it helps.

**Comment by LuboVarga** [comment]
Thanks, I have fixed things for our complex simulation with some rpc calls. I have also some builder support for making rpc calls easier stashed locally. I will try to put it into some branch if it is still "compatible".

**Pull request merged**
